### ISSUE TITLE
When getting the coverage.json file, the data is not being saved in the Project class, specifically in the ProjectParams and ProjectResults part

### ISSUE THREAD

**Issue by salet-gutierrez-jalafund** [SoftDevSix/ArgosApplication#31]
## Current Behavior

When making the request for the `/coverage/project/{id}` endpoint according to the project id, it should give me all the coverage of the project by taking the information from the coverage.json file, however, currently what happens is that when entering the project id, it does not return the coverage and gives me an error.

## Steps to Reproduce
Follow the steps in the video:

[https://drive.google.com/file/d/12jgAMsfqUDRwbd3c0DE9T-G8TW23KROw/view?usp=sharing](https://drive.google.com/file/d/12jgAMsfqUDRwbd3c0DE9T-G8TW23KROw/view?usp=sharing)

## Expected Behavior
What should happen is to show me the coverage of the project as defined in the `/coverage/project/{id}` enpoint.

## Context (Environment Information)
It affects the development of the API to obtain the coverage since it is not very clear why it is not being added, since currently the POST request of `/coverage/create-notification/projectCreationNotification` is added well in this [fix](https://github.com/SoftDevSix/ArgosApplication/pull/30) but it cannot be added to the Project.

## Possible solutions
See how to add to the Project entity correctly when obtaining the data from the json.

**Comment by zrock-dev** [comment]
fixed by #40
